version: '3'
services:
  my_api:
    image: ghcr.io/gthrm/nestjs-course/nestjs-course:develop
    container_name: my_api
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./.env:/opt/app/.env
