name: Publish Docker

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Publish to registry
        uses: elgohr/Publish-Docker-Github-Action@main
        with:
          registry: ghcr.io
          name: gthrm/nestjs-course/nestjs-course
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          tags: "develop"